name: animatediff
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pytorch-cuda=11.7
  - numpy==1.*
  - pip
  - pip:
    - diffusers==0.29.2
    - transformers==4.25.1
    - xformers==0.0.16
    - imageio==2.27.0
    - decord==0.6.0
    - gdown
    - einops
    - omegaconf
    - safetensors
    - gradio
    - wandb
    - matplotlib
    - peft==0.13.0
    - accelerate==1.0.0
    - onnxruntime