# animation-1
- domain_lora_scale: 1.0
  adapter_lora_path: "models/DreamBooth_LoRA/v3_sd15_adapter.ckpt"
  dreambooth_path:   "models/DreamBooth_LoRA/revAnimated_v2Rebirth.safetensors"
  ipa_path: ""

  inference_config: "configs/inference/inference.yaml"
  motion_module:    "models/Motion_with_LoRA/speedpainting.ckpt"

  controlnet_config: "configs/inference/sparsectrl/latent_condition_32.yaml"
  controlnet_path:   "models/ReferenceNet/speedpainting.ckpt"

  # seed: 42
  steps: 50
  guidance_scale: 5

  controlnet_image_indexes: [7]
  controlnet_images:
    - "/home/markus.pobitzer/data/datasets/video_as_pkl_combined/test/youtube/2jMFjnW7zJg/reference_frame.png"
    - "/home/markus.pobitzer/data/datasets/video_as_pkl_combined/test/youtube/3C-2uedxKcs/reference_frame.png"
    - "/home/markus.pobitzer/data/datasets/video_as_pkl_combined/test/youtube/4uMfPzeA528/reference_frame.png"
  controlnet_conditioning_scale: 1
  
  prompt:
    - "A sunset with trees in the foreground."
    - "A sunset with a lake and small islands with grass and trees."
    - "A forest scene in atumn with a lake."

  n_prompt:
    - "worst quality, low quality, letterboxed"

  ddim: true
  sample_size: 512